name: Build and Deploy .NET App to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev  
    
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ENV_JSON: ${{ vars.ENV_JSON }} # Accessing the environment-specific variable
      PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' 
      
    - name: Build .NET project
      run: dotnet build

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_USERNAME/dotnet-app:latest --label project=dotnet-app .

    - name: Log in to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push $DOCKER_USERNAME/dotnet-app:latest

    - name: Create .env file from ENV_JSON
      run: |
        # Convert JSON to .env format
         jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' <<< "$ENV_JSON" > .env
        
        # Verify the .env content
        echo "Copying .env file to EC2 instance..."
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        scp -q -o StrictHostKeyChecking=no -i github-ec2.pem .env ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/.env

    - name: AWS login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: SSH into EC2 instance and deploy container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Copy .env file to the EC2 instance
          scp -o StrictHostKeyChecking=no -i github-ec2.pem .env ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/.env
          
          # Pull the latest Docker image
          docker pull "${{ secrets.DOCKER_USERNAME }}/dotnet-app:latest"

          # Stop and remove the existing container if it exists
          if [ $(docker ps -q -f name=dotnet-app) ]; then
            echo "Stopping the existing container"
            docker stop dotnet-app
            docker rm dotnet-app
          fi
          
          # Run the new container
          docker run --env-file /home/${{ secrets.EC2_USERNAME }}/.env -p 8080:8080 -d --name dotnet-app "${{ secrets.DOCKER_USERNAME }}/dotnet-app:latest"

          # Remove .env file after deployment
          rm /home/${{ secrets.EC2_USERNAME }}/.env

          # Prune all unused Docker resources for this project
          docker system prune -f --filter "label=project=dotnet-app"

    - name: Send email notification
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}  # Your actual email address
        password: ${{ secrets.EMAIL_APP_PASSWORD }}  # Use App Password here
        subject: '${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}'
        body: '${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}'
        to: pankajkumarnikk@gmail.com
        from: sunny  # Your name or the name you'd like to show      
