name: Build and Deploy .NET App to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev  # Replace 'production' with your GitHub Environment name

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      ENV_JSON: ${{ github.event.environment.ENV_JSON }} # Accessing the environment-specific variable

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' # Specify your .NET version

    - name: Build .NET project
      run: dotnet build

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_USERNAME/dotnet-app:latest .

    - name: Log in to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push $DOCKER_USERNAME/dotnet-app:latest

    - name: Create .env file from ENV_JSON
      run: |
        run: |
        # Print the ENV_JSON content to debug
        echo "ENV_JSON content: $ENV_JSON"

        # Convert JSON to .env format
        echo "$ENV_JSON" | jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' > .env
        
        # Verify the .env content
        echo "Content of .env file:"
        cat .env

    - name: AWS login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: SSH into EC2 instance and deploy container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |


          
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker pull $DOCKER_USERNAME/dotnet-app:latest
          
  
          
          # Run the new container with the .env file
          docker run --env-file /home/${{ secrets.EC2_USERNAME }}/.env -p 8080:8080 -d --name dotnet-app $DOCKER_USERNAME/dotnet-app:latest
